image:
  # Koristi unapred definisanu Gitpod sliku koja ukljuÄuje git, docker i ostale alate
  file: .gitpod.Dockerfile

tasks:
  - name: Run VNC Desktop
    command: docker run -d -p 6080:80 dorowu/ubuntu-desktop-lxde-vnc
